# Generated by Django 2.2.13 on 2020-06-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='End_date',
            new_name='end_date',
        ),
    ]
