# Generated by Django 2.2.13 on 2020-06-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fixture',
        ),
    ]
