# Generated by Django 2.2.13 on 2020-06-18 02:32

import apps.tournament.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20200618_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(default=apps.tournament.models.now_plus_30),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
